name: cardio_env
channels:
  - defaults
dependencies:
  - python=3.12
  - pandas=2.2.2
  - numpy=1.26.4
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - xgboost=1.7.6
  - pip
  - pip:
      - streamlit==1.34.0
      - joblib==1.4.2
